//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class BMButtonSearch {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.Calendar calStartDate;
        protected System.Web.UI.WebControls.TextBox startDate;
        protected System.Web.UI.WebControls.Calendar calEndDate;
        protected System.Web.UI.WebControls.TextBox endDate;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submitBtn;
    }
}
