//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class BMCreateButton {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.WebControls.DropDownList buttonType;
        protected System.Web.UI.WebControls.DropDownList buttonCode;
        protected System.Web.UI.HtmlControls.HtmlInputText returnURL;
        protected System.Web.UI.HtmlControls.HtmlInputText itemName;
        protected System.Web.UI.HtmlControls.HtmlInputText businessMail;
        protected System.Web.UI.HtmlControls.HtmlInputText amount;
        protected System.Web.UI.HtmlControls.HtmlInputText billingCycles;
        protected System.Web.UI.HtmlControls.HtmlInputText installmentAmt;
        protected System.Web.UI.HtmlControls.HtmlInputText billingFreq;
        protected System.Web.UI.WebControls.DropDownList billingPeriod;
        protected System.Web.UI.WebControls.DropDownList optionType;
        protected System.Web.UI.HtmlControls.HtmlInputText shoppingUrl;
        protected System.Web.UI.HtmlControls.HtmlInputText minAmt;
        protected System.Web.UI.HtmlControls.HtmlInputText subTotal;
        protected System.Web.UI.HtmlControls.HtmlInputText subAmt;
        protected System.Web.UI.HtmlControls.HtmlInputText subPeriod;
        protected System.Web.UI.WebControls.DropDownList subInterval;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
