//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayPalAPISample.APICalls {
    
    public partial class BMSetInventory {
        protected System.Web.UI.HtmlControls.HtmlHead Head1;
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        protected System.Web.UI.HtmlControls.HtmlInputText hostedID;
        protected System.Web.UI.HtmlControls.HtmlInputText trackInv;
        protected System.Web.UI.HtmlControls.HtmlInputText trackPnl;
        protected System.Web.UI.HtmlControls.HtmlInputText itemNumber;
        protected System.Web.UI.HtmlControls.HtmlInputText itemQty;
        protected System.Web.UI.HtmlControls.HtmlInputText itemCost;
        protected System.Web.UI.HtmlControls.HtmlInputText itemAlert;
        protected System.Web.UI.HtmlControls.HtmlInputText soldoutURL;
        protected System.Web.UI.HtmlControls.HtmlInputSubmit submit;
    }
}
